name: CI/CD for PHP Application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.YGNISSHTESTKEYPAIR }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ygni.pem
          chmod 600 ~/.ssh/ygni.pem
          touch ~/.ssh/known_hosts
          ssh-keygen -R "[211.253.8.168]:10009"
          ssh-keyscan -p 10009 211.253.8.168 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/ygni.pem root@211.253.8.168 -p 10009 "sudo cp -R ./* /var/www/html/"
