name: CI/CD for PHP Application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: centos-7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy application
        run: |
          sudo cp -R ./* /var/www/html/
